-- MySQL Script generated by MySQL Workbench
-- Mon Jul 13 16:24:02 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema element_service_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `element_service_schema` ;

-- -----------------------------------------------------
-- Schema element_service_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `element_service_schema` DEFAULT CHARACTER SET utf8 ;
USE `element_service_schema` ;

-- -----------------------------------------------------
-- Table `Element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Element` ;

CREATE TABLE IF NOT EXISTS `Element` (
  `ElementID` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `atomic_number` INT NOT NULL,
  `symbol` VARCHAR(2) NOT NULL,
  `group` INT NULL,
  `period` INT NULL,
  `atomic_weight` FLOAT NULL,
  `density_grams_per_cubic_centimeter` FLOAT NULL,
  PRIMARY KEY (`ElementID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `symbol_UNIQUE` (`symbol` ASC),
  UNIQUE INDEX `atomic_number_UNIQUE` (`atomic_number` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
